# Generated by Django 4.2.6 on 2023-10-28 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiExpress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='servicios',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='telefono',
        ),
    ]
