# Generated by Django 4.2.6 on 2023-11-25 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServiExpress', '0002_alter_ordendecompra_id_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendecompra',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiExpress.producto'),
        ),
    ]
