# Generated by Django 4.2.2 on 2023-12-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiExpress', '0002_boleta'),
        ('ServiExpress', '0003_alter_ordendecompra_id_producto'),
    ]

    operations = [
    ]
