# Generated by Django 4.2.2 on 2023-12-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiExpress', '0004_merge_20231206_1248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boleta',
        ),
    ]
